use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use serde::Deserialize;

#[derive(Deserialize)]
struct Manifest {
    schema_version: u32,
    nodes: Vec<Coverage>,
}

#[derive(Deserialize)]
struct Coverage {
    nodedef: String,
    symbol: Option<String>,
    module: Option<String>,
    status: String,
}

const REQUIRED_NODEDEFS: &[&str] = &[
    "ND_surfacematerial",
    "ND_texcoord_vector2",
    "ND_constant_color3",
    "ND_constant_float",
    "ND_add_color3",
    "ND_add_float",
    "ND_multiply_color3",
    "ND_multiply_float",
    "ND_image_color3",
];

fn main() {
    let crate_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap());
    let translator = crate_dir.join("../../vendor/materialx-wesl/WESL");
    let coverage_path = translator.join("metadata/coverage.ron");
    let source_root = translator.join("src");

    println!("cargo:rerun-if-changed={}", coverage_path.display());
    println!("cargo:rerun-if-changed={}", source_root.display());

    let coverage_text = fs::read_to_string(&coverage_path).unwrap_or_else(|error| {
        panic!(
            "MaterialX descriptor is missing at {}: {error}. Initialize the vendor/materialx-wesl submodule.",
            coverage_path.display()
        )
    });
    let manifest: Manifest = ron::from_str(&coverage_text)
        .unwrap_or_else(|error| panic!("invalid MaterialX coverage.ron: {error}"));
    assert_eq!(
        manifest.schema_version, 1,
        "unsupported MaterialX registry schema"
    );

    let modules = collect_modules(&source_root);
    validate_required_nodes(&manifest, &modules);
    write_module_index(&modules);
}

fn collect_modules(source_root: &Path) -> BTreeMap<String, PathBuf> {
    fn visit(root: &Path, dir: &Path, out: &mut BTreeMap<String, PathBuf>) {
        for entry in fs::read_dir(dir).unwrap_or_else(|error| {
            panic!(
                "cannot read MaterialX WESL directory {}: {error}",
                dir.display()
            )
        }) {
            let path = entry.expect("valid directory entry").path();
            if path.is_dir() {
                visit(root, &path, out);
            } else if path.extension().and_then(|value| value.to_str()) == Some("wesl") {
                let relative = path.strip_prefix(root).expect("module below WESL root");
                let mut components: Vec<String> = relative
                    .components()
                    .map(|component| component.as_os_str().to_string_lossy().into_owned())
                    .collect();
                let last = components.last_mut().expect("WESL filename");
                *last = last.trim_end_matches(".wesl").to_string();
                let module = components.join("::");
                assert!(
                    out.insert(module.clone(), path).is_none(),
                    "duplicate MaterialX WESL module {module}"
                );
            }
        }
    }

    let mut modules = BTreeMap::new();
    visit(source_root, source_root, &mut modules);
    assert!(!modules.is_empty(), "MaterialX WESL module tree is empty");
    modules
}

fn validate_required_nodes(manifest: &Manifest, modules: &BTreeMap<String, PathBuf>) {
    for required in REQUIRED_NODEDEFS {
        let node = manifest
            .nodes
            .iter()
            .find(|node| node.nodedef == *required)
            .unwrap_or_else(|| panic!("required MaterialX NodeDef {required} is absent"));

        if matches!(node.status.as_str(), "translated" | "composed") {
            let module = node
                .module
                .as_deref()
                .unwrap_or_else(|| panic!("{required} has no WESL module"));
            let symbol = node
                .symbol
                .as_deref()
                .unwrap_or_else(|| panic!("{required} has no WESL symbol"));
            let source_path = modules
                .get(module)
                .unwrap_or_else(|| panic!("{required} refers to missing module {module}"));
            let source = fs::read_to_string(source_path).expect("read selected WESL module");
            assert!(
                source.contains(&format!("fn {symbol}(")),
                "{required} symbol {symbol} is absent from {module}"
            );
        }
    }
}

fn write_module_index(modules: &BTreeMap<String, PathBuf>) {
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").unwrap());
    let mut generated = String::from(
        "// @generated by crates/usd_bevy/build.rs; do not edit.\n\
         pub const TRANSLATOR_MODULES: &[(&str, &str, &str)] = &[\n",
    );
    for (module, path) in modules {
        let source_path = path.to_string_lossy();
        let asset_path = format!("embedded://materialx/{module}.wesl").replace("::", "/");
        generated.push_str(&format!(
            "    ({module:?}, {asset_path:?}, include_str!({source_path:?})),\n"
        ));
    }
    generated.push_str("];\n");
    fs::write(out_dir.join("materialx_modules.rs"), generated)
        .expect("write generated MaterialX module index");
}
